In [7]:
import pandas as pd

df = pd.read_csv(r"C:\Users\Afrotto\OneDrive\سطح المكتب\phone search (1).csv")

df.head()

,asin,product_title,product_price,product_original_price,currency,product_star_rating,product_num_ratings,product_num_offers,product_minimum_offer_price,is_best_seller,is_amazon_choice,is_prime,product_availability,climate_pledge_friendly,sales_volume,delivery,has_variations,unit_price,unit_count,coupon_text
0,B0BQ118F2T,Moto G Play 2023 3-Day Battery Unlocked Made f...,$99.00,$169.99,USD,4.0,1319,16,$69.88,False,False,True,Only 1 left in stock - order soon.,False,4K+ bought in past month,"FREE delivery Tue, Sep 24 Only 1 left in stock...",False,NaN,NaN,NaN
1,B0CV2W1TKZ,"Samsung Galaxy A15 (SM-155M/DSN), 128GB 6GB RA...",$153.99,NaN,USD,4.2,186,4,$147.50,False,False,True,NaN,False,1K+ bought in past month,"FREE delivery Tue, Sep 24",False,NaN,NaN,NaN
2,B09SM24S8C,"Samsung Galaxy A03s Cell Phone, AT&amp;T GSM U...",$69.00,$99.99,USD,3.8,597,35,$64.99,False,False,True,NaN,False,2K+ bought in past month,"FREE delivery Tue, Sep 24",True,NaN,NaN,NaN
3,B0CHH1N9VY,TracFone | Motorola Moto g Pure | Locked | 32G...,$49.99,NaN,USD,4.2,2814,3,$43.99,False,False,True,NaN,False,500+ bought in past month,"FREE delivery Tue, Sep 24",False,NaN,NaN,NaN
4,B09T3MQSVP,"Samsung Galaxy A13 5G Cell Phone, AT&amp;T GSM...",$88.09,$98.27,USD,3.8,1338,31,$70.40,False,False,True,NaN,False,500+ bought in past month,"FREE delivery Mon, Sep 30",False,NaN,NaN,NaN

In [8]:
df.shape

(340, 20)

In [9]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 340 entries, 0 to 339
Data columns (total 20 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   asin                         340 non-null    str
 1   product_title                340 non-null    str
 2   product_price                336 non-null    str
 3   product_original_price       148 non-null    str
 4   currency                     336 non-null    str
 5   product_star_rating          337 non-null    float64
 6   product_num_ratings          340 non-null    int64
 7   product_num_offers           340 non-null    int64
 8   product_minimum_offer_price  336 non-null    str
 9   is_best_seller               340 non-null    bool
 10  is_amazon_choice             340 non-null    bool
 11  is_prime                     340 non-null    bool
 12  product_availability         75 non-null     str
 13  climate_pledge_friendly      340 non-null    bool
 14  sales_volume                 320 non-null    str
 15  delivery                     337 non-null    str
 16  has_variations               340 non-null    bool
 17  unit_price                   4 non-null      str
 18  unit_count                   4 non-null      float64
 19  coupon_text                  22 non-null     str
dtypes: bool(5), float64(2), int64(2), str(11)
memory usage: 120.5 KB

In [10]:
df.isnull().sum()

asin                             0
product_title                    0
product_price                    4
product_original_price         192
currency                         4
product_star_rating              3
product_num_ratings              0
product_num_offers               0
product_minimum_offer_price      4
is_best_seller                   0
is_amazon_choice                 0
is_prime                         0
product_availability           265
climate_pledge_friendly          0
sales_volume                    20
delivery                         3
has_variations                   0
unit_price                     336
unit_count                     336
coupon_text                    318
dtype: int64

In [12]:
print("Rows before:", df.shape[0])

df = df.drop_duplicates(subset="asin")

print("Rows after:", df.shape[0])

Rows before: 340
Rows after: 315

In [13]:
df[['product_price',
    'product_original_price',
    'product_minimum_offer_price']].head()

  product_price product_original_price product_minimum_offer_price
0       $99.00                $169.99                      $69.88
1      $153.99                     NaN                    $147.50
2       $69.00                 $99.99                      $64.99
3       $49.99                     NaN                     $43.99
4       $88.09                 $98.27                      $70.40

In [14]:
price_cols = [
    'product_price',
    'product_original_price',
    'product_minimum_offer_price'
]

for col in price_cols:
    df[col] = df[col].str.replace('$', '', regex=False)
    df[col] = df[col].str.replace(',', '', regex=False)
    df[col] = pd.to_numeric(df[col], errors='coerce')

In [15]:
df[price_cols].head()

   product_price  product_original_price  product_minimum_offer_price
0          99.00                  169.99                        69.88
1         153.99                     NaN                       147.50
2          69.00                   99.99                        64.99
3          49.99                     NaN                        43.99
4          88.09                   98.27                        70.40

In [16]:
df[price_cols].dtypes

product_price                  float64
product_original_price         float64
product_minimum_offer_price    float64
dtype: object

In [17]:
df[['product_title']].head(20)

                                        product_title
0   Moto G Play 2023 3-Day Battery Unlocked Made f...
1   Samsung Galaxy A15 (SM-155M/DSN), 128GB 6GB RA...
2   Samsung Galaxy A03s Cell Phone, AT&amp;T GSM U...
3   TracFone | Motorola Moto g Pure | Locked | 32G...
4   Samsung Galaxy A13 5G Cell Phone, AT&amp;T GSM...
5   Panasonic Cordless Phone with Answering Machin...
6   Motorola Moto G 5G | 2023 | Unlocked | Made fo...
7   Samsung Galaxy A15 A155M 128GB Dual-SIM GSM Un...
8   Samsung Galaxy A15 A155M 128GB Dual-SIM GSM Un...
9   TracFone | Samsung Galaxy A03s | Locked | 32GB...
10  Motorola One Ace | 2021 | 2-Day Battery | Unlo...
11  Samsung Galaxy A25 5G A256E 128GB Dual-SIM GSM...
12  SAMSUNG Galaxy A15 5G A Series Cell Phone, 128...
13  OnePlus Nord N30 5G | Unlocked Dual-SIM Androi...
14  VTech DECT 6.0 Cordless Phone - Blue Display, ...
15  Apple iPhone 13 Mini, 128GB, Blue - Unlocked (...
30  Alcatel 1 (16GB) 5.0&quot; Full View Display, ...
31  Samsung Galaxy S21 Ultra 5G, US Version, 128GB...
32  SAMSUNG Galaxy S24+ Plus Cell Phone, 256GB AI ...
33  Samsung Galaxy A15 (SM-155M/DSN), 128GB 6GB RA...

In [18]:
df = df.reset_index(drop=True)

In [19]:
df[['product_title']].head(20)

                                        product_title
0   Moto G Play 2023 3-Day Battery Unlocked Made f...
1   Samsung Galaxy A15 (SM-155M/DSN), 128GB 6GB RA...
2   Samsung Galaxy A03s Cell Phone, AT&amp;T GSM U...
3   TracFone | Motorola Moto g Pure | Locked | 32G...
4   Samsung Galaxy A13 5G Cell Phone, AT&amp;T GSM...
5   Panasonic Cordless Phone with Answering Machin...
6   Motorola Moto G 5G | 2023 | Unlocked | Made fo...
7   Samsung Galaxy A15 A155M 128GB Dual-SIM GSM Un...
8   Samsung Galaxy A15 A155M 128GB Dual-SIM GSM Un...
9   TracFone | Samsung Galaxy A03s | Locked | 32GB...
10  Motorola One Ace | 2021 | 2-Day Battery | Unlo...
11  Samsung Galaxy A25 5G A256E 128GB Dual-SIM GSM...
12  SAMSUNG Galaxy A15 5G A Series Cell Phone, 128...
13  OnePlus Nord N30 5G | Unlocked Dual-SIM Androi...
14  VTech DECT 6.0 Cordless Phone - Blue Display, ...
15  Apple iPhone 13 Mini, 128GB, Blue - Unlocked (...
16  Alcatel 1 (16GB) 5.0&quot; Full View Display, ...
17  Samsung Galaxy S21 Ultra 5G, US Version, 128GB...
18  SAMSUNG Galaxy S24+ Plus Cell Phone, 256GB AI ...
19  Samsung Galaxy A15 (SM-155M/DSN), 128GB 6GB RA...

In [20]:
for title in df['product_title'].head(50):
    print(title)

Moto G Play 2023 3-Day Battery Unlocked Made for US 3/32GB 16MP Camera Navy Blue
Samsung Galaxy A15 (SM-155M/DSN), 128GB 6GB RAM, Dual SIM, Factory Unlocked GSM, International Version (Ring Grip Case Bundle) (Light Blue)
Samsung Galaxy A03s Cell Phone, AT&amp;T GSM Unlocked Android Smartphone, 32GB, Long Lasting Battery, Expandable Storage, 3 Camera Lenses, Infinite Display - Black (Renewed)
TracFone | Motorola Moto g Pure | Locked | 32GB | 4000 mAh Battery | 13 MP Dual Camera System | 6.5&quot; Max Vision HD+ Display | Blue
Samsung Galaxy A13 5G Cell Phone, AT&amp;T GSM Unlocked Android Smartphone, 64GB, Long Lasting Battery, Expandable Storage, Triple Lens Camera, Infinite Display, Black (Renewed)
Panasonic Cordless Phone with Answering Machine, Advanced Call Block, Bilingual Caller ID and Easy to Read High-Contrast Display, Expandable System with 2 Handsets - KX-TGD832M (Metallic Black)
Motorola Moto G 5G | 2023 | Unlocked | Made for US 4/128GB | 48 MPCamera | Ink Blue, 163.94x74.98x8.39
Samsung Galaxy A15 A155M 128GB Dual-SIM GSM Unlocked Android Smartphone (Latin America Version) - Light Blue
Samsung Galaxy A15 A155M 128GB Dual-SIM GSM Unlocked Android Smartphone (Latin America Version) - Blue Black
TracFone | Samsung Galaxy A03s | Locked | 32GB | 5000mAh Battery | 48MP Main Camera | 6.5-in. HD+Infinity-V Display | Black
Motorola One Ace | 2021 | 2-Day Battery | Unlocked | Made for US 4/64GB | 48MP Camera | Volcanic Gray
Samsung Galaxy A25 5G A256E 128GB Dual-SIM GSM Unlocked Android Smartphone (Latin Variant/US Compatible LTE) - Blue
SAMSUNG Galaxy A15 5G A Series Cell Phone, 128GB Unlocked Android Smartphone, AMOLED Display, Expandable Storage, Knox Security, Super Fast Charging, US Version, 2024, Blue Black
OnePlus Nord N30 5G | Unlocked Dual-SIM Android Smart Phone | 6.7&quot; LCD Display | 8 +128GB | 5000 mAh Battery | 50W Fast Charging | 108MP Camera | Chromatic Gray
VTech DECT 6.0 Cordless Phone - Blue Display, Big Buttons, Speakerphone, Caller ID, Easy Wall Mount, 1000ft Range - White/Grey
Apple iPhone 13 Mini, 128GB, Blue - Unlocked (Renewed)
Alcatel 1 (16GB) 5.0&quot; Full View Display, Removable Battery, FM Radio, Dual SIM GSM Unlocked US &amp; Global 4G LTE International Version 5033E (Bluish Black)
Samsung Galaxy S21 Ultra 5G, US Version, 128GB, Phantom Black - Unlocked (Renewed)
SAMSUNG Galaxy S24+ Plus Cell Phone, 256GB AI Smartphone, Unlocked Android, 50MP Camera, Fastest Processor, Long Battery Life, US Version, 2024, Onyx Black
Samsung Galaxy A15 (SM-155M/DSN), 128GB 6GB RAM, Dual SIM, Factory Unlocked GSM, International Version (Wall Charger Bundle) (Light Blue)
Bold K10 | 2024 | 3-Day Battery | Unlocked | 6.6” HD+ Infinity Display | 128/4GB | Triple 50MP Camera | US Version | US Warranty | Black
AT&amp;T BL102-3 DECT 6.0 3-Handset Cordless Phone for Home with Answering Machine, Call Blocking, Caller ID Announcer, Audio Assist, Intercom, and Unsurpassed Range, Silver/Black
SAMSUNG Galaxy S23 FE AI Phone, 128GB Unlocked Android Smartphone, Long Battery Life, Premium Processor, Tough Gorilla Glass Display, Hi-Res 50MP Camera, US Version, 2023, Mint
BLU G63 | 2023 | 3-Day Battery | Unlocked | 6.8” HD+ Infinity Display | 128/4GB | Dual 13MP Camera | US Version | US Warranty | Green
Nokia C2 2E | Android 11 (Go Edition) | Unlocked Smartphone | All Day Battery | 2/32GB | 5.7-Inch Screen | International Version | Blue
Google Pixel 4a with 5G - Android Phone - New Unlocked Smartphone with Night Sight and Ultrawide Lens - Just Black
AT&amp;T TRIMLINE 213 Corded Home Phone with Extra Big Buttons &amp; Visual Ringer. No AC Power Required, Improved Easy-Wall-Mount, Lighted Keypad, 10 Speed Dial Keys, Volume Control, Senior Friendly. White
Samsung Galaxy S20 FE 5G, 128GB, Cloud Navy - Unlocked (Renewed)
Total by Verizon | Samsung Galaxy A03s | Locked | 32GB | 5000mAh Battery | 48MP Main Camera | 6.5-in. HD+Infinity-V Display | Black
TracFone Moto g Pure (2021), 32GB, Blue - Prepaid Smartphone (Locked/Renewed)
Google Pixel 7a - Unlocked Android Cell Phone - Smartphone with Wide Angle Lens and 24-Hour Battery - 128 GB – Charcoal
SAMSUNG Galaxy A15 5G (SM-156M/DSN), 256GB 8GB RAM, Dual SIM, Factory Unlocked GSM, International Version (Wall Charger Bundle) (Light Blue)
TCL ION Z Unlock Smartphone 4G LTE 32GB - Black
I14 Pro Max Unlocked Smartphone, 6+256GB, Android 13.0 Unlocked Cell Phones, 6.82&quot; HD Screen Battery 6800mAH with 128GB Memory Card/Face ID/Fingerprint Lock/Dual SIM 5G Phone (Blue)
TracFone TCL Flip 2, 8GB, Black - Prepaid Flip Phone (Locked)
Apple iPhone 12 Mini, 64GB, Black - Unlocked (Renewed)
Samsung Galaxy S23 Fan Edition(FE) 5G (SM-S711B/DS) Dual SIM,256GB + 8GB, Factory Unlocked, International Version - No Warranty - (Purple)
Google Pixel 5 - 5G Android Phone - Water Resistant - Unlocked Smartphone with Night Sight and Ultrawide Lens - Just Black
Samsung Galaxy A14 5G A Series, Factory Unlocked, 64GB, US Version, Black (Renewed)
Tracfone Samsung Galaxy A14 5G Locked 64GB 5000mAh Battery 50 MP triple-camera system 6.6-in. FHD+ LCD Display Black
Samsung Galaxy S21 5G, US Version, 128GB, Phantom Gray - Unlocked (Renewed)
Motorola razr | 2023 | Unlocked | Made for US 8/128 | 32MP Camera | Summer Lilac, 73.95 x 170.82 x 7.35mm
Panasonic DECT 6.0 Expandable Cordless Phone System with Answering Machine and Call Blocking - 3 Handsets - KX-TGE633M (Metallic Black)
Apple iPhone SE 2nd Generation, US Version, 64GB, Black - Unlocked (Renewed)
Alcatel SMARTFLIP 4052R | 4G LTE | 4GB Flip-Phone | Bluetooth, WiFi, Big Buttons | Carrier locked to AT&amp;T. Phone is not unlocked - Volcano Black
Apple iPhone 12 Pro, 128GB, Pacific Blue - Fully Unlocked (Renewed)
Motorola Moto Edge 5G UW 256gb Nebula Blue for Verizon (Renewed)
Samsung Galaxy S21 Ultra 5G, US Version, 256GB, Phantom Black - Unlocked (Renewed)
Apple iPhone 12, 128GB, Black - Fully Unlocked (Renewed)
SAMSUNG Galaxy S24 Cell Phone, 256GB AI Smartphone, Unlocked Android, 50MP Camera, Fastest Processor, Long Battery Life, US Version, 2024, Marble Gray

In [21]:
exclude_words = [
    'cordless',
    'corded',
    'dect',
    'answering machine',
    'trimline',
    'wall mount',
    'speakerphone',
    'landline',
    'home phone',
    'telephone',
    'smartflip',
    'flip phone'
]

In [22]:
pattern = '|'.join(exclude_words)

phones_df = df[
    ~df['product_title']
    .str.lower()
    .str.contains(pattern, na=False)
]

In [23]:
print("Rows before filter:", len(df))
print("Rows after filter:", len(phones_df))

Rows before filter: 315
Rows after filter: 237

In [24]:
phones_df[['product_title']].head(20)

                                        product_title
0   Moto G Play 2023 3-Day Battery Unlocked Made f...
1   Samsung Galaxy A15 (SM-155M/DSN), 128GB 6GB RA...
2   Samsung Galaxy A03s Cell Phone, AT&amp;T GSM U...
3   TracFone | Motorola Moto g Pure | Locked | 32G...
4   Samsung Galaxy A13 5G Cell Phone, AT&amp;T GSM...
6   Motorola Moto G 5G | 2023 | Unlocked | Made fo...
7   Samsung Galaxy A15 A155M 128GB Dual-SIM GSM Un...
8   Samsung Galaxy A15 A155M 128GB Dual-SIM GSM Un...
9   TracFone | Samsung Galaxy A03s | Locked | 32GB...
10  Motorola One Ace | 2021 | 2-Day Battery | Unlo...
11  Samsung Galaxy A25 5G A256E 128GB Dual-SIM GSM...
12  SAMSUNG Galaxy A15 5G A Series Cell Phone, 128...
13  OnePlus Nord N30 5G | Unlocked Dual-SIM Androi...
15  Apple iPhone 13 Mini, 128GB, Blue - Unlocked (...
16  Alcatel 1 (16GB) 5.0&quot; Full View Display, ...
17  Samsung Galaxy S21 Ultra 5G, US Version, 128GB...
18  SAMSUNG Galaxy S24+ Plus Cell Phone, 256GB AI ...
19  Samsung Galaxy A15 (SM-155M/DSN), 128GB 6GB RA...
20  Bold K10 | 2024 | 3-Day Battery | Unlocked | 6...
22  SAMSUNG Galaxy S23 FE AI Phone, 128GB Unlocked...

In [25]:
brands = [
    'Samsung',
    'Apple',
    'Motorola',
    'Google',
    'OnePlus',
    'Nokia',
    'BLU',
    'TCL',
    'Alcatel'
]

for brand in brands:
    print(brand, ":", phones_df['product_title'].str.contains(brand, case=False, na=False).sum())

Samsung : 89
Apple : 17
Motorola : 32
Google : 13
OnePlus : 9
Nokia : 6
BLU : 50
TCL : 1
Alcatel : 2

In [26]:
phones_df.shape

(237, 20)

In [27]:
def extract_brand(title):
    
    title = str(title).lower()

    if 'samsung' in title:
        return 'Samsung'
    elif 'iphone' in title or 'apple' in title:
        return 'Apple'
    elif 'motorola' in title or 'moto' in title:
        return 'Motorola'
    elif 'google' in title or 'pixel' in title:
        return 'Google'
    elif 'oneplus' in title:
        return 'OnePlus'
    elif 'nokia' in title:
        return 'Nokia'
    elif 'blu' in title:
        return 'BLU'
    elif 'tcl' in title:
        return 'TCL'
    elif 'alcatel' in title:
        return 'Alcatel'
    else:
        return 'Other'

In [28]:
phones_df['Brand'] = phones_df['product_title'].apply(extract_brand)

In [29]:
phones_df['Brand'].value_counts()

Brand
Samsung     89
Other       46
Motorola    37
Apple       25
Google      13
BLU         10
OnePlus      9
Nokia        6
TCL          1
Alcatel      1
Name: count, dtype: int64

In [30]:
phones_df[phones_df['Brand'] == 'Other'][['product_title']].head(30)

                                         product_title
20   Bold K10 | 2024 | 3-Day Battery | Unlocked | 6...
92   DOOGEE S118 4G Rugged Smartphone Unlocked,MTK ...
97   Kyocera DuraForce Pro 2 with Sapphire Shield E...
105  DOOGEE N55 Android 14 Cell Phone,9GB+128GB Exp...
111  Cat S22 Flip (16GB) 2.8&quot; Touchscreen, And...
113  Reno 11 Pro Unlocked Android Phone 6.7-inch HD...
115  CUBOT KingKong X Rugged Smartphone 5G- 32GB RA...
119  DOOGEE Blade 10 Rugged Phone Unlocked Android ...
123  Bold K50 | 5G| 2024 | 3-Day Battery | Unlocked...
125  UMIDIGI G9 5G Cell Phone, Android 14 Unlocked ...
133  Kyocera DuraXV Extreme E4810 Verizon Rugged LT...
151  Nothing Phone (2a) Smartphone Unlocked 5G Andr...
161  SIMBROS Radiant Core Phone At&amp;t Unlocked u...
175  CAT S62 Rugged Cell Phone Unlocked (128GB, 4GB...
177  NUU A15 Cell Phone 4GB + 128GB, Unlocked for M...
185  X40 Unlocked 5G Cell Phones 2024 Android 13 Mo...
192  Blackview Rugged Smartphone Unlocked, 2023 BV6...
195  DOOGEE Blade 10 Ultra Rugged Smartphone, 20GB ...
199  Prepaid At&amp;T Axia 4G LTE 16GB Android 8.1 ...
206  LIVELY Jitterbug Flip2 - Flip Cell Phone for S...
210  CMF Phone 1 8+256GB - Unlocked Smartphone with...
229  Xiaomi Redmi Note 13 4G LTE (256GB + 8GB) 6.67...
230  X3 2024 New Cheap 4G LTE GSM Unlocked Android ...
236  Gabb Phone 4 Pro The Safe Phone Built for Teen...
238  X1 2024 New 4G LTE GSM Unlocked Cell Phone 6.5...
241  OUKITEL G1 Rugged Smartphone Unlocked - 24+256...
254  KYOCERA New E4830 DuraXE Epic AT&amp;T/Unlocke...
257  NUU A23Plus Basic Cell Phone for AT&amp;T, T-M...
258  Kids Smart Phone for Girls, Christmas Birthday...
260  ZTE Cymbal 4G LTE speed &quot;Verizon Prepaid&...

In [31]:
phones_df['sales_volume'].dropna().unique()[:30]

<ArrowStringArray>
[ '4K+ bought in past month',  '1K+ bought in past month',
  '2K+ bought in past month', '500+ bought in past month',
 '400+ bought in past month', '200+ bought in past month',
 '300+ bought in past month',  '50+ bought in past month',
 '100+ bought in past month',                    'List: ',
       'More Buying Choices',                 'Typical: ',
           'Typical price: ',  '3K+ bought in past month']
Length: 14, dtype: str

In [36]:
phones_df['sales_volume_clean'].describe()

KeyError: 'sales_volume_clean'

In [37]:
clean_sales

In [38]:
phones_df['sales_volume_clean'] = phones_df['sales_volume'].apply(clean_sales)

NameError: name 'np' is not defined

In [39]:
clean_sales('4K+ bought in past month')

4000.0

In [40]:
phones_df['sales_volume'].head()

0     4K+ bought in past month
1     1K+ bought in past month
2     2K+ bought in past month
3    500+ bought in past month
4    500+ bought in past month
Name: sales_volume, dtype: str

In [41]:
phones_df['sales_volume_clean'] = phones_df['sales_volume'].apply(clean_sales)

NameError: name 'np' is not defined

In [42]:
for x in phones_df['sales_volume'].dropna().unique():
    try:
        print(x, " --> ", clean_sales(x))
    except Exception as e:
        print("ERROR:", x)
        print(e)

4K+ bought in past month  -->  4000.0
1K+ bought in past month  -->  1000.0
2K+ bought in past month  -->  2000.0
500+ bought in past month  -->  500.0
400+ bought in past month  -->  400.0
200+ bought in past month  -->  200.0
300+ bought in past month  -->  300.0
50+ bought in past month  -->  50.0
100+ bought in past month  -->  100.0
ERROR: List:
name 'np' is not defined
ERROR: More Buying Choices
name 'np' is not defined
ERROR: Typical:
name 'np' is not defined
ERROR: Typical price:
name 'np' is not defined
3K+ bought in past month  -->  3000.0

In [43]:
import numpy as np

In [44]:
phones_df['sales_volume_clean'] = phones_df['sales_volume'].apply(clean_sales)

In [45]:
phones_df[['sales_volume','sales_volume_clean']].head(20)

                 sales_volume  sales_volume_clean
0    4K+ bought in past month              4000.0
1    1K+ bought in past month              1000.0
2    2K+ bought in past month              2000.0
3   500+ bought in past month               500.0
4   500+ bought in past month               500.0
6    2K+ bought in past month              2000.0
7   500+ bought in past month               500.0
8    1K+ bought in past month              1000.0
9    1K+ bought in past month              1000.0
10   1K+ bought in past month              1000.0
11  400+ bought in past month               400.0
12   2K+ bought in past month              2000.0
13   1K+ bought in past month              1000.0
15  500+ bought in past month               500.0
16   1K+ bought in past month              1000.0
17   2K+ bought in past month              2000.0
18   1K+ bought in past month              1000.0
19   4K+ bought in past month              4000.0
20  200+ bought in past month               200.0
22  200+ bought in past month               200.0

In [46]:
phones_df[['sales_volume_clean']].describe()

       sales_volume_clean
count          198.000000
mean           495.202020
std            676.839257
min             50.000000
25%            100.000000
50%            300.000000
75%            500.000000
max           4000.000000

In [47]:
phones_df.isnull().sum()

asin                             0
product_title                    0
product_price                    4
product_original_price         137
currency                         4
product_star_rating              3
product_num_ratings              0
product_num_offers               0
product_minimum_offer_price      4
is_best_seller                   0
is_amazon_choice                 0
is_prime                         0
product_availability           169
climate_pledge_friendly          0
sales_volume                    16
delivery                         3
has_variations                   0
unit_price                     237
unit_count                     237
coupon_text                    223
Brand                            0
sales_volume_clean              39
dtype: int64

In [48]:
phones_df = phones_df.dropna(
    subset=[
        'product_price',
        'product_star_rating'
    ]
)

In [49]:
phones_df.shape

(230, 22)

In [50]:
df = pd.read_csv(r"C:\Users\Afrotto\OneDrive\سطح المكتب\phone search (1).csv")

df.head()

,asin,product_title,product_price,product_original_price,currency,product_star_rating,product_num_ratings,product_num_offers,product_minimum_offer_price,is_best_seller,is_amazon_choice,is_prime,product_availability,climate_pledge_friendly,sales_volume,delivery,has_variations,unit_price,unit_count,coupon_text
0,B0BQ118F2T,Moto G Play 2023 3-Day Battery Unlocked Made f...,$99.00,$169.99,USD,4.0,1319,16,$69.88,False,False,True,Only 1 left in stock - order soon.,False,4K+ bought in past month,"FREE delivery Tue, Sep 24 Only 1 left in stock...",False,NaN,NaN,NaN
1,B0CV2W1TKZ,"Samsung Galaxy A15 (SM-155M/DSN), 128GB 6GB RA...",$153.99,NaN,USD,4.2,186,4,$147.50,False,False,True,NaN,False,1K+ bought in past month,"FREE delivery Tue, Sep 24",False,NaN,NaN,NaN
2,B09SM24S8C,"Samsung Galaxy A03s Cell Phone, AT&amp;T GSM U...",$69.00,$99.99,USD,3.8,597,35,$64.99,False,False,True,NaN,False,2K+ bought in past month,"FREE delivery Tue, Sep 24",True,NaN,NaN,NaN
3,B0CHH1N9VY,TracFone | Motorola Moto g Pure | Locked | 32G...,$49.99,NaN,USD,4.2,2814,3,$43.99,False,False,True,NaN,False,500+ bought in past month,"FREE delivery Tue, Sep 24",False,NaN,NaN,NaN
4,B09T3MQSVP,"Samsung Galaxy A13 5G Cell Phone, AT&amp;T GSM...",$88.09,$98.27,USD,3.8,1338,31,$70.40,False,False,True,NaN,False,500+ bought in past month,"FREE delivery Mon, Sep 30",False,NaN,NaN,NaN

In [51]:
phones_df.columns

Index(['asin', 'product_title', 'product_price', 'product_original_price',
       'currency', 'product_star_rating', 'product_num_ratings',
       'product_num_offers', 'product_minimum_offer_price', 'is_best_seller',
       'is_amazon_choice', 'is_prime', 'product_availability',
       'climate_pledge_friendly', 'sales_volume', 'delivery', 'has_variations',
       'unit_price', 'unit_count', 'coupon_text', 'Brand',
       'sales_volume_clean'],
      dtype='str')

In [52]:
phones_df.head()

,asin,product_title,product_price,product_original_price,currency,product_star_rating,product_num_ratings,product_num_offers,product_minimum_offer_price,is_best_seller,...,product_availability,climate_pledge_friendly,sales_volume,delivery,has_variations,unit_price,unit_count,coupon_text,Brand,sales_volume_clean
0,B0BQ118F2T,Moto G Play 2023 3-Day Battery Unlocked Made f...,99.00,169.99,USD,4.0,1319,16,69.88,False,...,Only 1 left in stock - order soon.,False,4K+ bought in past month,"FREE delivery Tue, Sep 24 Only 1 left in stock...",False,NaN,NaN,NaN,Motorola,4000.0
1,B0CV2W1TKZ,"Samsung Galaxy A15 (SM-155M/DSN), 128GB 6GB RA...",153.99,NaN,USD,4.2,186,4,147.50,False,...,NaN,False,1K+ bought in past month,"FREE delivery Tue, Sep 24",False,NaN,NaN,NaN,Samsung,1000.0
2,B09SM24S8C,"Samsung Galaxy A03s Cell Phone, AT&amp;T GSM U...",69.00,99.99,USD,3.8,597,35,64.99,False,...,NaN,False,2K+ bought in past month,"FREE delivery Tue, Sep 24",True,NaN,NaN,NaN,Samsung,2000.0
3,B0CHH1N9VY,TracFone | Motorola Moto g Pure | Locked | 32G...,49.99,NaN,USD,4.2,2814,3,43.99,False,...,NaN,False,500+ bought in past month,"FREE delivery Tue, Sep 24",False,NaN,NaN,NaN,Motorola,500.0
4,B09T3MQSVP,"Samsung Galaxy A13 5G Cell Phone, AT&amp;T GSM...",88.09,98.27,USD,3.8,1338,31,70.40,False,...,NaN,False,500+ bought in past month,"FREE delivery Mon, Sep 30",False,NaN,NaN,NaN,Samsung,500.0

In [53]:
import re

def extract_storage(title):

    title = str(title)

    match = re.search(r'(\d+)\s?GB', title, re.IGNORECASE)

    if match:
        return int(match.group(1))

    return np.nan

In [54]:
phones_df['Storage_GB'] = phones_df['product_title'].str.extract(r'(\d+)\s?GB', expand=False)

In [55]:
phones_df[['product_title','Storage_GB']].head(10)

                                        product_title Storage_GB
0   Moto G Play 2023 3-Day Battery Unlocked Made f...         32
1   Samsung Galaxy A15 (SM-155M/DSN), 128GB 6GB RA...        128
2   Samsung Galaxy A03s Cell Phone, AT&amp;T GSM U...         32
3   TracFone | Motorola Moto g Pure | Locked | 32G...         32
4   Samsung Galaxy A13 5G Cell Phone, AT&amp;T GSM...         64
6   Motorola Moto G 5G | 2023 | Unlocked | Made fo...        128
7   Samsung Galaxy A15 A155M 128GB Dual-SIM GSM Un...        128
8   Samsung Galaxy A15 A155M 128GB Dual-SIM GSM Un...        128
9   TracFone | Samsung Galaxy A03s | Locked | 32GB...         32
10  Motorola One Ace | 2021 | 2-Day Battery | Unlo...         64

In [56]:
phones_df['Product_Name'] = phones_df['product_title']

In [57]:
phones_df[['product_title','Product_Name']].head()

,product_title,Product_Name
0,Moto G Play 2023 3-Day Battery Unlocked Made f...,Moto G Play 2023 3-Day Battery Unlocked Made f...
1,"Samsung Galaxy A15 (SM-155M/DSN), 128GB 6GB RA...","Samsung Galaxy A15 (SM-155M/DSN), 128GB 6GB RA..."
2,"Samsung Galaxy A03s Cell Phone, AT&amp;T GSM U...","Samsung Galaxy A03s Cell Phone, AT&amp;T GSM U..."
3,TracFone | Motorola Moto g Pure | Locked | 32G...,TracFone | Motorola Moto g Pure | Locked | 32G...
4,"Samsung Galaxy A13 5G Cell Phone, AT&amp;T GSM...","Samsung Galaxy A13 5G Cell Phone, AT&amp;T GSM..."

In [58]:
phones_df['RAM_GB'] = phones_df['product_title'].str.extract(r'(\d+)\s?GB\s?RAM', expand=False)

In [59]:
phones_df[['product_title','Storage_GB','RAM_GB']].head(10)

                                        product_title Storage_GB RAM_GB
0   Moto G Play 2023 3-Day Battery Unlocked Made f...         32    NaN
1   Samsung Galaxy A15 (SM-155M/DSN), 128GB 6GB RA...        128      6
2   Samsung Galaxy A03s Cell Phone, AT&amp;T GSM U...         32    NaN
3   TracFone | Motorola Moto g Pure | Locked | 32G...         32    NaN
4   Samsung Galaxy A13 5G Cell Phone, AT&amp;T GSM...         64    NaN
6   Motorola Moto G 5G | 2023 | Unlocked | Made fo...        128    NaN
7   Samsung Galaxy A15 A155M 128GB Dual-SIM GSM Un...        128    NaN
8   Samsung Galaxy A15 A155M 128GB Dual-SIM GSM Un...        128    NaN
9   TracFone | Samsung Galaxy A03s | Locked | 32GB...         32    NaN
10  Motorola One Ace | 2021 | 2-Day Battery | Unlo...         64    NaN

In [60]:
phones_df[['Brand','Storage_GB','RAM_GB']].head(20)

       Brand Storage_GB RAM_GB
0   Motorola         32    NaN
1    Samsung        128      6
2    Samsung         32    NaN
3   Motorola         32    NaN
4    Samsung         64    NaN
6   Motorola        128    NaN
7    Samsung        128    NaN
8    Samsung        128    NaN
9    Samsung         32    NaN
10  Motorola         64    NaN
11   Samsung        128    NaN
12   Samsung        128    NaN
13   OnePlus        128    NaN
15     Apple        128    NaN
16       BLU         16    NaN
17   Samsung        128    NaN
18   Samsung        256    NaN
19   Samsung        128      6
20     Other          4    NaN
22   Samsung        128    NaN

In [61]:
phones_df['Storage_GB'].value_counts(dropna=False)

Storage_GB
128    80
NaN    34
32     29
64     22
256    22
16     12
8       9
512     6
4       4
20      3
6       3
9       2
1       1
3       1
2       1
25      1
Name: count, dtype: int64

In [62]:
phones_df = phones_df.drop(columns=['Product_Name'])

In [63]:
phones_df['Storage_GB'] = phones_df['Storage_GB'].apply(
    lambda x: x if pd.isna(x) or x >= 16 else np.nan
)

TypeError: '>=' not supported between instances of 'str' and 'int'

In [64]:
phones_df['Storage_GB'] = pd.to_numeric(
    phones_df['Storage_GB'],
    errors='coerce'
)

In [65]:
phones_df['Storage_GB'] = phones_df['Storage_GB'].apply(
    lambda x: x if pd.isna(x) or x >= 16 else np.nan
)

In [66]:
phones_df['Storage_GB'].value_counts(dropna=False)

Storage_GB
128.0    80
NaN      55
32.0     29
64.0     22
256.0    22
16.0     12
512.0     6
20.0      3
25.0      1
Name: count, dtype: int64

In [67]:
phones_df = phones_df.drop(columns=['Product_Name'])

KeyError: "['Product_Name'] not found in axis"

In [68]:
phones_df['Brand'].value_counts()

Brand
Samsung     86
Other       46
Motorola    36
Apple       25
Google      13
BLU          9
OnePlus      8
Nokia        6
Alcatel      1
Name: count, dtype: int64

In [69]:
phones_df.groupby('Brand')['product_price'].mean().sort_values(ascending=False)

Brand
OnePlus     436.975000
Google      329.051538
Samsung     255.955814
Apple       192.024800
Other       145.525217
Motorola    139.305278
BLU          89.101111
Nokia        60.491667
Alcatel      59.990000
Name: product_price, dtype: float64

In [70]:
phones_df.groupby('Brand')['product_star_rating'].mean().sort_values(ascending=False)

Brand
Apple       4.284000
Google      4.184615
OnePlus     4.175000
Motorola    4.122222
Samsung     4.077907
Other       3.997826
Alcatel     3.800000
BLU         3.655556
Nokia       3.483333
Name: product_star_rating, dtype: float64

In [72]:
phones_df.groupby('Brand')['sales_volume_clean'].mean().sort_values(ascending=False)

Brand
Apple       661.363636
Samsung     584.146341
Nokia       508.333333
Motorola    494.230769
OnePlus     414.285714
BLU         360.000000
Google      358.333333
Other       297.142857
Alcatel            NaN
Name: sales_volume_clean, dtype: float64

In [73]:
phones_df['Storage_GB'].value_counts()

Storage_GB
128.0    80
32.0     29
64.0     22
256.0    22
16.0     12
512.0     6
20.0      3
25.0      1
Name: count, dtype: int64

In [74]:
phones_df.groupby('Storage_GB')['product_price'].mean().sort_values()

Storage_GB
32.0      84.358621
64.0     126.885000
25.0     139.000000
128.0    221.614750
20.0     259.990000
16.0     272.817500
256.0    447.937273
512.0    835.755000
Name: product_price, dtype: float64

In [75]:
phones_df[['Brand','product_title','product_price']]\
.sort_values(by='product_price', ascending=False)\
.head(10)

       Brand                                      product_title  product_price
129  Samsung  SAMSUNG Galaxy Z Fold 6 AI Cell Phone, 512GB U...        1614.99
176  OnePlus  OnePlus Open, 16GB RAM+512GB, Dual-SIM, Voyage...        1299.99
290   Google  Google Pixel 9 Pro XL - Unlocked Android Smart...        1199.00
291  Samsung  SAMSUNG Galaxy S24 Ultra 5G S9280 Physical Dua...         993.90
213  Samsung  SAMSUNG Galaxy Z Flip 6 AI Cell Phone, 512GB U...         944.96
81   Samsung  SAMSUNG Galaxy S24 Cell Phone, 256GB AI Smartp...         859.99
173  Samsung  SAMSUNG Galaxy S24 Cell Phone, 256GB AI Smartp...         859.99
57   Samsung  Samsung Galaxy S23 Ultra 5G SM-S918B/DS Dual S...         799.99
86   OnePlus  OnePlus 12,16GB RAM+512GB,Dual-SIM,Unlocked An...         799.99
18   Samsung  SAMSUNG Galaxy S24+ Plus Cell Phone, 256GB AI ...         798.00

In [76]:
phones_df[['Brand','product_title','product_star_rating']]\
.sort_values(by='product_star_rating', ascending=False)\
.head(10)

,Brand,product_title,product_star_rating
263,Other,A23 Unlocked Android Phone 6.7-inch HD LCD Unl...,5.0
286,Motorola,Motorola Moto G04 XT2421-2 (Dual Sim) Factory ...,5.0
185,Other,X40 Unlocked 5G Cell Phones 2024 Android 13 Mo...,5.0
195,Other,"DOOGEE Blade 10 Ultra Rugged Smartphone, 20GB ...",5.0
208,Samsung,"SAMSUNG Galaxy A05s (SM-A057M/DS), 128GB 4GB R...",5.0
174,Apple,"Magnetic for iPhone 16 Case,[Compatible with M...",5.0
191,Apple,"TEAM LUXURY for iPhone 15 Case, [Military Grad...",4.8
310,Apple,"Gimbal Stabilizer for Smartphone, 3-Axis Phone...",4.7
33,BLU,"I14 Pro Max Unlocked Smartphone, 6+256GB, Andr...",4.7
306,Other,"Prepaid USA SIM Card, 25GB/365 Day, 4G LTE &am...",4.7

In [77]:
phones_df.to_csv(
    'phones_cleaned.csv',
    index=False
)

In [1]:
import os

print(os.path.abspath('phones_cleaned.csv'))

C:\Users\Afrotto\phones_cleaned.csv